services:
        disp851_1:
            image: 'dispasu:v1.1.0'
            build: Disp/
            command: node app.js ConfigurationDispatching851ASU.json
            ports:
             - 4905:4905
            volumes:
             - /home/sedatec/DockerConfig/ПС851:/usr/src/app/View/SeDaTec.Main.Dispatching/Configuration
             - /home/sedatec/DockerConfig/ПС851:/usr/src/app/Components/SeDaTec.Component.MQTT/Configuration
             - /home/sedatec/DockerConfig/ПС851:/usr/src/app/Components/SeDaTec.Component.Info/Configuration
             - /home/sedatec/Img:/usr/src/app/View/UserPhotos
        disp851_2:
            image: 'dispdc:v1.1.0'
            build: Disp/
            command: node app.js ConfigurationDispatching851DC.json
            ports:
             - 4907:4907
            volumes:
             - /home/sedatec/DockerConfig/ПС851:/usr/src/app/View/SeDaTec.Main.Dispatching/Configuration
             - /home/sedatec/DockerConfig/ПС851:/usr/src/app/Components/SeDaTec.Component.MQTT/Configuration
             - /home/sedatec/DockerConfig/ПС851:/usr/src/app/Components/SeDaTec.Component.Info/Configuration
             - /home/sedatec/Img:/usr/src/app/View/UserPhotos
        disp851_3:
            image: 'dispgs:v1.1.0'
            build: DispGS/
            command: node app.js ConfigurationDispatching851GS.json
            ports:
             - 4904:4904
            volumes:
             - /home/sedatec/DockerConfig/ПС851:/usr/src/app/View/SeDaTec.View.DispatchingGS/Configuration
             - /home/sedatec/DockerConfig/ПС851:/usr/src/app/Components/SeDaTec.Component.MQTT/Configuration
             - /home/sedatec/DockerConfig/ПС851:/usr/src/app/Components/SeDaTec.Component.Info/Configuration
             - /home/sedatec/Img:/usr/src/app/View/UserPhotos
        disp851_4:
            image: 'dispmt:v1.1.0'
            build: Disp/
            command: node app.js ConfigurationDispatching851MT.json
            ports:
             - 4901:4901
            volumes:
             - /home/sedatec/DockerConfig/ПС851:/usr/src/app/View/SeDaTec.Main.Dispatching/Configuration
             - /home/sedatec/DockerConfig/ПС851:/usr/src/app/Components/SeDaTec.Component.MQTT/Configuration
             - /home/sedatec/DockerConfig/ПС851:/usr/src/app/Components/SeDaTec.Component.Info/Configuration
             - /home/sedatec/Img:/usr/src/app/View/UserPhotos
        disp851_5:
            image: 'dispmt:v1.1.0'
            build: Disp/
            command: node app.js ConfigurationDispatching851TPZ.json
            ports:
             - 4902:4902
            volumes:
             - /home/sedatec/DockerConfig/ПС851:/usr/src/app/View/SeDaTec.Main.Dispatching/Configuration
             - /home/sedatec/DockerConfig/ПС851:/usr/src/app/Components/SeDaTec.Component.MQTT/Configuration
             - /home/sedatec/DockerConfig/ПС851:/usr/src/app/Components/SeDaTec.Component.Info/Configuration
             - /home/sedatec/Img:/usr/src/app/View/UserPhotos
        disp851_6:
            image: 'dispwt:v1.1.0'
            build: Disp/
            command: node app.js ConfigurationDispatching851WT.json
            ports:
             - 4908:4908
            volumes:
             - /home/sedatec/DockerConfig/ПС851:/usr/src/app/View/SeDaTec.Main.Dispatching/Configuration
             - /home/sedatec/DockerConfig/ПС851:/usr/src/app/Components/SeDaTec.Component.MQTT/Configuration
             - /home/sedatec/DockerConfig/ПС851:/usr/src/app/Components/SeDaTec.Component.Info/Configuration
             - /home/sedatec/Img:/usr/src/app/View/UserPhotos
        disp851_7:
            image: 'dispvn:v1.1.0'
            build: Disp/
            command: node app.js ConfigurationDispatching851VN3.json
            ports:
             - 4906:4906
            volumes:
             - /home/sedatec/DockerConfig/ПС851:/usr/src/app/View/SeDaTec.Main.Dispatching/Configuration
             - /home/sedatec/DockerConfig/ПС851:/usr/src/app/Components/SeDaTec.Component.MQTT/Configuration
             - /home/sedatec/DockerConfig/ПС851:/usr/src/app/Components/SeDaTec.Component.Info/Configuration
             - /home/sedatec/Img:/usr/src/app/View/UserPhotos
        disp851_8:
            image: 'dispvn:v1.1.0'
            build: Disp/
            command: node app.js ConfigurationDispatching851VN6.json
            ports:
             - 4909:4909
            volumes:
             - /home/sedatec/DockerConfig/ПС851:/usr/src/app/View/SeDaTec.Main.Dispatching/Configuration
             - /home/sedatec/DockerConfig/ПС851:/usr/src/app/Components/SeDaTec.Component.MQTT/Configuration
             - /home/sedatec/DockerConfig/ПС851:/usr/src/app/Components/SeDaTec.Component.Info/Configuration
             - /home/sedatec/Img:/usr/src/app/View/UserPhotos
       
        gs851_1:
            image: 'gsall:v1.0.8'
            build: GS/
            restart: always
            command: node appGS.js ConfigurationGS851.json
            volumes:
             - /home/sedatec/DockerConfig/ПС851:/usr/src/app/System/SeDaTec.System.GS/Configuration
             - /home/sedatec/DockerConfig/ПС851:/usr/src/app/Components/SeDaTec.Component.MQTT/Configuration
             - /home/sedatec/DockerConfig/ПС851:/usr/src/app/Components/SeDaTec.Component.Info/Configuration
        ReadArch:
            image: 'arh:v1.0.5'
            build: ReadArch/
            command: node app.js ConfigurationArchRT851.json
            ports:
             - 4938:4938
            volumes:
             - /home/sedatec/DockerConfig/ПС851:/usr/src/app/View/SeDaTec.View.ArchMain/Configuration
             - /home/sedatec/DockerConfig/ПС851:/usr/src/app/View/SeDaTec.View.ArchMain/ArchivePostgresReader/Configuration
             - /home/sedatec/DockerConfig/ПС851:/usr/src/app/Components/SeDaTec.Component.MQTT/Configuration
             - /home/sedatec/DockerConfig/ПС851:/usr/src/app/Components/SeDaTec.Component.Info/Configuration
             - /home/sedatec/Img:/usr/src/app/View/UserPhotos 
        Gal:
            image: 'gal:v1.1.0'
            build: Gal/
            command: node app.js ConfigurationGallery.json
            ports:
             - 4977:4977
            volumes:
             - /home/sedatec/DockerConfig/ПС851:/usr/src/app/View/SeDaTec.View.Gallery/Configuration
             - /home/sedatec/DockerConfig/ПС851:/usr/src/app/Components/SeDaTec.Component.MQTT/Configuration
             - /home/sedatec/DockerBuilder/PC851/Gal/View/SeDaTec.View.Gallery/Server/app_settings/uploads:/usr/src/app/View/SeDaTec.View.Gallery/Server/app_settings/uploads
             - /home/sedatec/Img:/usr/src/app/View/UserPhotos
              
