services:
        disp864_1:
            image: 'dispasu:v1.1.0'
            build: Disp/
            command: node app.js ConfigurationDispatching864ASU.json
            ports:
             - 4205:4205
            volumes:
             - /home/sedatec/DockerConfig/ПС864:/usr/src/app/View/SeDaTec.Main.Dispatching/Configuration
             - /home/sedatec/DockerConfig/ПС864:/usr/src/app/Components/SeDaTec.Component.MQTT/Configuration
             - /home/sedatec/DockerConfig/ПС864:/usr/src/app/Components/SeDaTec.Component.Info/Configuration
             - /home/sedatec/Img:/usr/src/app/View/UserPhotos
        disp864_2:
            image: 'dispdc:v1.1.0'
            build: Disp/
            command: node app.js ConfigurationDispatching864DC1.json
            ports:
             - 4207:4207
            volumes:
             - /home/sedatec/DockerConfig/ПС864:/usr/src/app/View/SeDaTec.Main.Dispatching/Configuration
             - /home/sedatec/DockerConfig/ПС864:/usr/src/app/Components/SeDaTec.Component.MQTT/Configuration
             - /home/sedatec/DockerConfig/ПС864:/usr/src/app/Components/SeDaTec.Component.Info/Configuration
             - /home/sedatec/Img:/usr/src/app/View/UserPhotos
        disp864_2_1:
            image: 'dispdc:v1.1.0'
            build: Disp/
            command: node app.js ConfigurationDispatching864DC2.json
            ports:
             - 4209:4209
            volumes:
             - /home/sedatec/DockerConfig/ПС864:/usr/src/app/View/SeDaTec.Main.Dispatching/Configuration
             - /home/sedatec/DockerConfig/ПС864:/usr/src/app/Components/SeDaTec.Component.MQTT/Configuration
             - /home/sedatec/DockerConfig/ПС864:/usr/src/app/Components/SeDaTec.Component.Info/Configuration
             - /home/sedatec/Img:/usr/src/app/View/UserPhotos    
        disp864_3:
            image: 'dispgs:v1.1.0'
            build: DispGS/
            command: node app.js ConfigurationDispatching864GS.json
            ports:
             - 4203:4203
            volumes:
             - /home/sedatec/DockerConfig/ПС864:/usr/src/app/View/SeDaTec.View.DispatchingGS/Configuration
             - /home/sedatec/DockerConfig/ПС864:/usr/src/app/Components/SeDaTec.Component.MQTT/Configuration
             - /home/sedatec/DockerConfig/ПС864:/usr/src/app/Components/SeDaTec.Component.Info/Configuration
             - /home/sedatec/Img:/usr/src/app/View/UserPhotos
        disp864_4:
            image: 'dispmt:v1.1.0'
            build: Disp/
            command: node app.js ConfigurationDispatching864MT1.json
            ports:
             - 4201:4201
            volumes:
             - /home/sedatec/DockerConfig/ПС864:/usr/src/app/View/SeDaTec.Main.Dispatching/Configuration
             - /home/sedatec/DockerConfig/ПС864:/usr/src/app/Components/SeDaTec.Component.MQTT/Configuration
             - /home/sedatec/DockerConfig/ПС864:/usr/src/app/Components/SeDaTec.Component.Info/Configuration
             - /home/sedatec/Img:/usr/src/app/View/UserPhotos
        disp864_5:
            image: 'dispmt:v1.1.0'
            build: Disp/
            command: node app.js ConfigurationDispatching864MT2.json
            ports:
             - 4202:4202
            volumes:
             - /home/sedatec/DockerConfig/ПС864:/usr/src/app/View/SeDaTec.Main.Dispatching/Configuration
             - /home/sedatec/DockerConfig/ПС864:/usr/src/app/Components/SeDaTec.Component.MQTT/Configuration
             - /home/sedatec/DockerConfig/ПС864:/usr/src/app/Components/SeDaTec.Component.Info/Configuration
             - /home/sedatec/Img:/usr/src/app/View/UserPhotos
        disp864_6:
            image: 'dispwt:v1.1.0'
            build: Disp/
            command: node app.js ConfigurationDispatching864WT.json
            ports:
             - 4208:4208
            volumes:
             - /home/sedatec/DockerConfig/ПС864:/usr/src/app/View/SeDaTec.Main.Dispatching/Configuration
             - /home/sedatec/DockerConfig/ПС864:/usr/src/app/Components/SeDaTec.Component.MQTT/Configuration
             - /home/sedatec/DockerConfig/ПС864:/usr/src/app/Components/SeDaTec.Component.Info/Configuration
             - /home/sedatec/Img:/usr/src/app/View/UserPhotos
        disp864_7:
            image: 'disppd:v1.1.0'
            build: Disp/
            command: node app.js ConfigurationDispatching864CHR.json
            ports:
             - 4210:4210    
            volumes:
             - /home/sedatec/DockerConfig/ПС864:/usr/src/app/View/SeDaTec.Main.Dispatching/Configuration
             - /home/sedatec/DockerConfig/ПС864:/usr/src/app/Components/SeDaTec.Component.MQTT/Configuration
             - /home/sedatec/DockerConfig/ПС864:/usr/src/app/Components/SeDaTec.Component.Info/Configuration
             - /home/sedatec/Img:/usr/src/app/View/UserPhotos
        ReadArch:
            image: 'arh:v1.0.5'
            build: ReadArch/
            command: node app.js ConfigurationArchRT864.json
            ports:
             - 4238:4238
            volumes:
             - /home/sedatec/DockerConfig/ПС864:/usr/src/app/View/SeDaTec.View.ArchMain/Configuration
             - /home/sedatec/DockerConfig/ПС864:/usr/src/app/View/SeDaTec.View.ArchMain/ArchivePostgresReader/Configuration
             - /home/sedatec/DockerConfig/ПС864:/usr/src/app/Components/SeDaTec.Component.MQTT/Configuration
             - /home/sedatec/DockerConfig/ПС864:/usr/src/app/Components/SeDaTec.Component.Info/Configuration
             - /home/sedatec/Img:/usr/src/app/View/UserPhotos   
        Gal:
            image: 'gal:v1.1.0'
            build: Gal/
            command: node app.js ConfigurationGallery.json
            ports:
             - 4277:4277
            volumes:
             - /home/sedatec/DockerConfig/ПС864:/usr/src/app/View/SeDaTec.View.Gallery/Configuration
             - /home/sedatec/DockerConfig/ПС864:/usr/src/app/Components/SeDaTec.Component.MQTT/Configuration
             - /home/sedatec/DockerBuilder/PC864/Gal/View/SeDaTec.View.Gallery/Server/app_settings/uploads:/usr/src/app/View/SeDaTec.View.Gallery/Server/app_settings/uploads
             - /home/sedatec/Img:/usr/src/app/View/UserPhotos
              

        gs864_1:
            image: 'gsall:v1.0.8'
            restart: always
            build: GS/
            command: node appGS.js ConfigurationGS864.json
            volumes:
             - /home/sedatec/DockerConfig/ПС864:/usr/src/app/System/SeDaTec.System.GS/Configuration
             - /home/sedatec/DockerConfig/ПС864:/usr/src/app/Components/SeDaTec.Component.MQTT/Configuration
             - /home/sedatec/DockerConfig/ПС864:/usr/src/app/Components/SeDaTec.Component.Info/Configuration
