services:
        disp861_1:
            image: 'dispasu:v1.1.0'
            build: Disp/
            command: node app.js ConfigurationDispatching861ASU.json
            ports:
             - 5005:5005
            volumes:
             - /home/sedatec/DockerConfig/ПС861:/usr/src/app/View/SeDaTec.Main.Dispatching/Configuration
             - /home/sedatec/DockerConfig/ПС861:/usr/src/app/Components/SeDaTec.Component.MQTT/Configuration
             - /home/sedatec/DockerConfig/ПС861:/usr/src/app/Components/SeDaTec.Component.Info/Configuration
             - /home/sedatec/Img:/usr/src/app/View/UserPhotos
        disp861_2:
            image: 'dispdc:v1.1.0'
            build: Disp/
            command: node app.js ConfigurationDispatching861DC1.json
            ports:
             - 5007:5007
            volumes:
             - /home/sedatec/DockerConfig/ПС861:/usr/src/app/View/SeDaTec.Main.Dispatching/Configuration
             - /home/sedatec/DockerConfig/ПС861:/usr/src/app/Components/SeDaTec.Component.MQTT/Configuration
             - /home/sedatec/DockerConfig/ПС861:/usr/src/app/Components/SeDaTec.Component.Info/Configuration
             - /home/sedatec/Img:/usr/src/app/View/UserPhotos
        disp861_2_2:
            image: 'dispdc:v1.1.0'
            build: Disp/
            command: node app.js ConfigurationDispatching861DC2.json
            ports:
             - 5009:5009
            volumes:
             - /home/sedatec/DockerConfig/ПС861:/usr/src/app/View/SeDaTec.Main.Dispatching/Configuration
             - /home/sedatec/DockerConfig/ПС861:/usr/src/app/Components/SeDaTec.Component.MQTT/Configuration
             - /home/sedatec/DockerConfig/ПС861:/usr/src/app/Components/SeDaTec.Component.Info/Configuration
             - /home/sedatec/Img:/usr/src/app/View/UserPhotos
        disp861_3:
            image: 'dispgs:v1.1.0'
            build: DispGS/
            command: node app.js ConfigurationDispatching861GS.json
            ports:
             - 5003:5003
            volumes:
             - /home/sedatec/DockerConfig/ПС861:/usr/src/app/View/SeDaTec.View.DispatchingGS/Configuration
             - /home/sedatec/DockerConfig/ПС861:/usr/src/app/Components/SeDaTec.Component.MQTT/Configuration
             - /home/sedatec/DockerConfig/ПС861:/usr/src/app/Components/SeDaTec.Component.Info/Configuration
             - /home/sedatec/Img:/usr/src/app/View/UserPhotos
        disp861_4:
            image: 'dispmt:v1.1.0'
            build: Disp/
            command: node app.js ConfigurationDispatching861TMS1.json
            ports:
             - 5001:5001
            volumes:
             - /home/sedatec/DockerConfig/ПС861:/usr/src/app/View/SeDaTec.Main.Dispatching/Configuration
             - /home/sedatec/DockerConfig/ПС861:/usr/src/app/Components/SeDaTec.Component.MQTT/Configuration
             - /home/sedatec/DockerConfig/ПС861:/usr/src/app/Components/SeDaTec.Component.Info/Configuration
             - /home/sedatec/Img:/usr/src/app/View/UserPhotos
        disp861_5:
            image: 'dispmt:v1.1.0'
            build: Disp/
            command: node app.js ConfigurationDispatching861TMS2.json
            ports:
             - 5002:5002
            volumes:
             - /home/sedatec/DockerConfig/ПС861:/usr/src/app/View/SeDaTec.Main.Dispatching/Configuration
             - /home/sedatec/DockerConfig/ПС861:/usr/src/app/Components/SeDaTec.Component.MQTT/Configuration
             - /home/sedatec/DockerConfig/ПС861:/usr/src/app/Components/SeDaTec.Component.Info/Configuration
             - /home/sedatec/Img:/usr/src/app/View/UserPhotos
        disp861_6:
            image: 'disptm:v1.1.0'
            build: Disp/
            command: node app.js ConfigurationDispatching861TM.json
            ports:
             - 5008:5008
            volumes:
             - /home/sedatec/DockerConfig/ПС861:/usr/src/app/View/SeDaTec.Main.Dispatching/Configuration
             - /home/sedatec/DockerConfig/ПС861:/usr/src/app/Components/SeDaTec.Component.MQTT/Configuration
             - /home/sedatec/DockerConfig/ПС861:/usr/src/app/Components/SeDaTec.Component.Info/Configuration
             - /home/sedatec/Img:/usr/src/app/View/UserPhotos
        disp861_7:
            image: 'dispwt:v1.1.0'
            build: Disp/
            command: node app.js ConfigurationDispatching861WT.json
            ports:
             - 5010:5010
            volumes:
             - /home/sedatec/DockerConfig/ПС861:/usr/src/app/View/SeDaTec.Main.Dispatching/Configuration
             - /home/sedatec/DockerConfig/ПС861:/usr/src/app/Components/SeDaTec.Component.MQTT/Configuration
             - /home/sedatec/DockerConfig/ПС861:/usr/src/app/Components/SeDaTec.Component.Info/Configuration
             - /home/sedatec/Img:/usr/src/app/View/UserPhotos
        ReadArch:
            image: 'arh:v1.0.5'
            build: ReadArch/
            command: node app.js ConfigurationArchRT861.json
            ports:
             - 5038:5038
            volumes:
             - /home/sedatec/DockerConfig/ПС861:/usr/src/app/View/SeDaTec.View.ArchMain/Configuration
             - /home/sedatec/DockerConfig/ПС861:/usr/src/app/View/SeDaTec.View.ArchMain/ArchivePostgresReader/Configuration
             - /home/sedatec/DockerConfig/ПС861:/usr/src/app/Components/SeDaTec.Component.MQTT/Configuration
             - /home/sedatec/DockerConfig/ПС861:/usr/src/app/Components/SeDaTec.Component.Info/Configuration
             - /home/sedatec/Img:/usr/src/app/View/UserPhotos

        gs861_1:
            image: 'gsall:v1.0.8'
            restart: always
            build: GS/
            command: node appGS.js ConfigurationGS861.json
            volumes:
             - /home/sedatec/DockerConfig/ПС861:/usr/src/app/System/SeDaTec.System.GS/Configuration
             - /home/sedatec/DockerConfig/ПС861:/usr/src/app/Components/SeDaTec.Component.MQTT/Configuration
             - /home/sedatec/DockerConfig/ПС861:/usr/src/app/Components/SeDaTec.Component.Info/Configuration
        Gal:
            image: 'gal:v1.1.0'
            build: Gal/
            command: node app.js ConfigurationGallery.json
            ports:
             - 5077:5077
            volumes:
             - /home/sedatec/DockerConfig/ПС861:/usr/src/app/View/SeDaTec.View.Gallery/Configuration
             - /home/sedatec/DockerConfig/ПС861:/usr/src/app/Components/SeDaTec.Component.MQTT/Configuration
             - /home/sedatec/DockerBuilder/PC861/Gal/View/SeDaTec.View.Gallery/Server/app_settings/uploads:/usr/src/app/View/SeDaTec.View.Gallery/Server/app_settings/uploads
             - /home/sedatec/Img:/usr/src/app/View/UserPhotos
      
  

       
